export const FETCH_PRODUCT = 'FETCH_PRODUCT'

export const ADD_TO_CART = 'ADD_TO_CART'
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY'
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY'
export const DELETE_CART = 'DELETE_CART'
export const UPDATE_CART = 'UPDATE_CART'

